:verbose: false
:timeout: 8
:concurrency: 2
:queues:
  - default
  - critical
  - low
  - mailers
  - action_mailbox_routing
  - action_mailbox_incineration
  - active_storage_analysis
  - active_storage_purge
